image: rust:slim
stages:
  - setup
  - test

cache: 
  key: build-cache
  paths: 
    - cargo-registry
    - target/

setup-rustup:
  stage: setup
  script:
    - rustup toolchain update stable
    - rustup toolchain update beta
    - rustup toolchain update nightly
  before_script:
    - rm -rf /usr/local/cargo/registry || true
    - mv cargo-registry /usr/local/cargo/registry || true
  after_script:
    - mv /usr/local/cargo/registry cargo-registry || true

.test-template: &test-template
  stage: test
  before_script:
    - rm -rf /usr/local/cargo/registry || true
    - mv cargo-registry /usr/local/cargo/registry || true
    - export RUST_BACKTRACE=1
    - rustup default "$RUST_TOOLCHAIN"
    - rustup --version
    - rustc --version
    - cargo --version
  script:
    - cargo test --tests --jobs 1
    - cargo test --tests --jobs 1 --release
    - cargo test --features doctest --doc --jobs 1
    - cargo test --features doctest --doc --jobs 1 --release
    - cargo test --no-default-features --tests --jobs 1
    - cargo test --no-default-features --tests --jobs 1 --release
  after_script:
    - mv /usr/local/cargo/registry cargo-registry || true

test-stable:
  <<: *test-template
  variables:
    RUST_TOOLCHAIN:  stable

test-beta:
  <<: *test-template
  variables:
    RUST_TOOLCHAIN:  beta

test-nightly:
  <<: *test-template
  variables:
    RUST_TOOLCHAIN:  nightly

test-coverage:
  <<: *test-template
  variables:
    RUST_TOOLCHAIN: stable
  script:
    - cargo install cargo-tarpaulin -f
    - cargo tarpaulin --verbose

test-fmt:
  <<: *test-template
  variables:
    RUST_TOOLCHAIN: stable
  script:
    - rustup component add rustfmt
    - cargo fmt --all --verbose -- --check

test-clippy:
  <<: *test-template
  variables:
    RUST_TOOLCHAIN: stable
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings
    - cargo clippy --no-default-features -- -D warnings

test-docs:
  <<: *test-template
  variables:
    RUST_TOOLCHAIN: nightly
  script:
    - rustc --version && cargo --version
    - cargo doc --no-deps
